name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        latest-node-version: [20.x]
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v1
      - name: Build with Node.js ${{ matrix.latest-node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.latest-node-version }}
      - name: Build and test with latest
        run: |
          npm install
          npm run build
          npm run test:only
      - name: Switch to Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test node
        run: |
          node dist/trace-mapping.umd.js
      - name: Benchmark
        run: |
          npm run benchmark:install
          npm run benchmark:only
        env:
          CI: true
